[package]
name = "vault-test"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "/home/dungdv/source/Aptos/aptos-core/aptos-move/framework/aptos-framework" }
[addresses]
std =  "0x1"
vault = "0x1103"